name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: promise/containerapps-album-backend # ${{ github.repository }}

jobs:
  dockerloginbuildpush:
  #build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build ./src/ --file ./src/Dockerfile --tag album-api:$(date +%s)
      
    - name: Log in to the GitHub Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: ./src
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v1 # ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
